spring.application.name=milky-way

# Nạp file .env
spring.config.import=optional:file:.env[.properties]

# Ánh xạ chính xác
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER_NAME}
spring.datasource.password=${DATABASE_PASSWORD}